# Generated by Django 4.2 on 2024-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.CharField(choices=[('Routine', 'การทำงานตามหน้าที่'), ('Special', 'การทำงานมอบหมาย'), ('Other', 'การทำงานอื่นๆ')], default='Routine', max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('In Progress', 'กำลังทำงาน'), ('Done', 'เสร็จสมบูรณ์'), ('Cancelled', 'ยกเลิก')], default='In Progress', max_length=200),
        ),
        migrations.DeleteModel(
            name='JournalStatus',
        ),
        migrations.DeleteModel(
            name='JournalType',
        ),
    ]
