# Generated by Django 4.1.1 on 2022-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignprogress',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
