# Generated by Django 4.2 on 2024-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_alter_assign_options_assign_ref_inform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='body',
            field=models.TextField(),
        ),
    ]
