# Generated by Django 4.2 on 2024-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_alter_assign_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignprogress',
            name='status',
            field=models.CharField(choices=[('Pending', 'รอตอบรับ'), ('Accepted', 'ตอบรับแล้ว'), ('Rejected', 'ปฏิเสธ'), ('Done', 'เสร็จสมบูรณ์')], default='Pending', max_length=20),
        ),
    ]
