# Generated by Django 4.1.1 on 2023-03-20 16:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inform.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0005_profile_department"),
        ("asset", "0009_alter_stockitem_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_category",
                    models.CharField(
                        choices=[("HW", "อุปกรณ์"), ("SW", "ระบบ"), ("OT", "อื่น ๆ")],
                        max_length=8,
                    ),
                ),
                ("issue", ckeditor.fields.RichTextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("HIG", "สูงสุด"),
                            ("MED", "ปานกลาง"),
                            ("LOW", "ทั่วไป"),
                        ],
                        default="LOW",
                        max_length=8,
                    ),
                ),
                (
                    "inform_status",
                    models.CharField(
                        choices=[
                            ("INF", "แจ้งซ่อม"),
                            ("WAT", "รออนุมัติ"),
                            ("REJ", "ยกเลิก"),
                        ],
                        default="INF",
                        max_length=8,
                    ),
                ),
                (
                    "approve_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APR", "อนุมัติ"),
                            ("RJT", "ไม่อนุมัติ"),
                            ("RCK", "ตรวจสอบใหม่"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "repair_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAT", "รอวงรอบ"),
                            ("URG", "ซ่อมด่วน"),
                            ("AGN", "ซ่อมโดย จนท.ประจำสถานี"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "repair_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RPR", "ซ่อม"),
                            ("CMP", "ดำเนินการแล้ว"),
                            ("REJ", "ยกเลิก"),
                            ("CLO", "ปิดงาน"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stockitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockitem",
                        to="asset.stockitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to=inform.models.inform_image)),
                (
                    "inform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inform_image",
                        to="inform.inform",
                    ),
                ),
            ],
        ),
    ]
