# Generated by Django 4.2 on 2023-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
