# Generated by Django 4.2 on 2023-06-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_inform_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_progress', to='inform.inform')),
            ],
        ),
    ]
