# Generated by Django 4.2 on 2023-07-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_informprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informprogress',
            name='status',
            field=models.CharField(blank=True, choices=[('RPR', 'ซ่อม'), ('CMP', 'ดำเนินการแล้ว'), ('REJ', 'ยกเลิก'), ('CLO', 'ปิดงาน')], default='RPR', max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='InformReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_reject', to='inform.inform')),
            ],
        ),
    ]
