# Generated by Django 4.2 on 2023-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0004_alter_informprogress_status_informreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
