# Generated by Django 4.2 on 2024-01-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0012_alter_inform_repair_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inform',
            options={'ordering': ['-created_at']},
        ),
    ]
