# Generated by Django 4.2 on 2025-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0013_alter_inform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='issue',
            field=models.TextField(),
        ),
    ]
