# Generated by Django 4.2 on 2025-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0014_alter_inform_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='issue_category',
            field=models.CharField(choices=[('HW', 'อุปกรณ์'), ('SW', 'ระบบ'), ('RP', 'ทดแทน'), ('OT', 'อื่น ๆ')], max_length=8),
        ),
    ]
