# Generated by Django 4.2 on 2023-11-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
