# Generated by Django 4.2 on 2024-11-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='account.sector'),
        ),
    ]
