# Generated by Django 4.2 on 2023-09-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0012_alter_stockitem_serial'),
        ('inform', '0012_alter_inform_repair_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatteliteStockBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inform_request', models.BooleanField(default=False)),
                ('inform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inform.inform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='RelayStockBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inform_request', models.BooleanField(default=False)),
                ('inform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inform.inform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='DataStockBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inform_request', models.BooleanField(default=False)),
                ('inform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inform.inform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='AirStockBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inform_request', models.BooleanField(default=False)),
                ('inform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inform.inform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
            ],
        ),
    ]
