# Generated by Django 4.1.1 on 2022-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_department_assigned_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='department',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
