# Generated by Django 4.1.1 on 2022-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_assigned_user_remove_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='recieved',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Document/%Y/%B/%d/'),
        ),
    ]
