# Generated by Django 4.1.1 on 2022-10-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_department_recieved_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
