# Generated by Django 4.2 on 2024-11-22 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_document_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Depart',
        ),
    ]
