# Generated by Django 4.1.1 on 2022-12-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='StockItem/Categories/'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
