# Generated by Django 4.1.1 on 2022-12-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_category_image_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.network'),
        ),
    ]
