# Generated by Django 4.1.1 on 2022-12-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('พร้อมใช้งาน', 'Available'), ('กำลังใช้งาน', 'In Use'), ('ซ่อมบำรุง', 'Under Maintenance'), ('จำหน่าย', 'Disposed')], default='พร้อมใช้งาน', max_length=20),
        ),
    ]
