# Generated by Django 4.2 on 2023-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
