# Generated by Django 4.2 on 2023-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_stockitem_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='count_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
