# Generated by Django 4.2 on 2024-01-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_itemonhand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemonhand',
            name='updated_at',
        ),
    ]
