# Generated by Django 4.2 on 2024-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_stockitem_location_setup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='location_setup',
            new_name='location_install',
        ),
    ]
