# Generated by Django 4.2 on 2024-04-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_rename_location_setup_stockitem_location_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemonhand',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem'),
        ),
    ]
