# Generated by Django 4.2 on 2024-04-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        ('asset', '0022_alter_itemonhand_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='account.department'),
        ),
        migrations.AlterField(
            model_name='itemonhand',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem'),
        ),
    ]
