# Generated by Django 4.2 on 2024-04-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        ('asset', '0023_stockitem_stock_alter_itemonhand_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='dept_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_used', to='account.department'),
        ),
    ]
