# Generated by Django 4.2 on 2024-04-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        ('asset', '0024_remove_stockitem_stock_stockitem_dept_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='dept_used',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='location',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_control', to='account.department'),
        ),
    ]
