# Generated by Django 4.2 on 2024-11-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        ('asset', '0027_alter_stockitem_stock_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='location_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_item', to='account.department'),
        ),
    ]
