# Generated by Django 4.2 on 2024-11-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        ('asset', '0028_stockitem_location_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='location_install',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_install', to='account.department'),
        ),
    ]
