# Generated by Django 4.1.1 on 2022-11-02 13:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Approve Status',
                'verbose_name_plural': 'Approve Status',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_max', models.FloatField(default=40)),
                ('fuel_rate', models.FloatField(default=0.0)),
                ('fuel_now', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mile_now', models.PositiveIntegerField(default=0)),
                ('responsible_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_man', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Car',
            },
        ),
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuel', models.PositiveIntegerField(default=0)),
                ('refueled_at', models.DateTimeField(auto_now_add=True)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('refueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refueler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refuel',
                'verbose_name_plural': 'Refuel',
            },
        ),
        migrations.CreateModel(
            name='CarUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('passenger', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('mile_current', models.PositiveIntegerField(blank=True, null=True)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_use', models.FloatField(default=0.0)),
                ('approve_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_approve_status', to='car.approvestatus')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_approver', to='account.profile')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='account.profile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_car', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Use',
                'verbose_name_plural': 'Car Use',
            },
        ),
        migrations.CreateModel(
            name='CarFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cost_expect', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('cost_use', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('approve_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_approve_status', to='car.approvestatus')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_approver', to='account.profile')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('fix_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Fix',
                'verbose_name_plural': 'Car Fix',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_status', to='car.carstatus'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cartype'),
        ),
    ]
