# Generated by Django 4.1.1 on 2022-11-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='responsible_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_man', to='account.profile'),
        ),
    ]
