# Generated by Django 4.1.1 on 2022-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Car/'),
        ),
    ]
