# Generated by Django 4.1.1 on 2022-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_car_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
