# Generated by Django 4.1.1 on 2022-11-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user'),
        ('car', '0008_rename_caruse_carbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbooking',
            options={'verbose_name': 'Car Booking', 'verbose_name_plural': 'Car Booking'},
        ),
        migrations.AddField(
            model_name='carbooking',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='passenger',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
