# Generated by Django 4.1.1 on 2022-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_carbooking_options_carbooking_control_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='control',
            new_name='controler',
        ),
    ]
