# Generated by Django 4.1.1 on 2022-11-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_rename_control_carbooking_controler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='car.car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='get_image_name'),
        ),
    ]
