# Generated by Django 4.1.1 on 2022-11-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_carbooking_car_alter_carimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfix',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fix', to='car.car'),
        ),
    ]
