# Generated by Django 4.1.1 on 2022-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_refuel_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mile_now',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='mile_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='refuel',
            field=models.FloatField(default=0.0),
        ),
    ]
