# Generated by Django 4.1.1 on 2022-12-01 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_car_mile_now_alter_carbooking_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
