# Generated by Django 4.1.1 on 2022-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_rename_mile_current_carbooking_mile_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='mile_refuel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
