# Generated by Django 4.1.1 on 2022-12-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_remove_carfix_cost_expect_alter_carfix_cost_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAfterFixImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='get_image_fix')),
                ('fix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carfix')),
            ],
        ),
    ]
