# Generated by Django 4.1.1 on 2022-12-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user'),
        ('car', '0019_carafterfiximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFixStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Car Fix Status',
                'verbose_name_plural': 'Car Fix Status',
            },
        ),
        migrations.AddField(
            model_name='carfix',
            name='responsible_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='account.profile'),
        ),
        migrations.AddField(
            model_name='carfix',
            name='fix_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_status', to='car.carfixstatus'),
        ),
    ]
