# Generated by Django 4.1.1 on 2022-12-20 12:34

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_carfixstatus_carfix_responsible_man_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfiximage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.get_image_fix),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.get_image_name),
        ),
    ]
