# Generated by Django 4.1.1 on 2023-01-16 09:23

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_alter_carfiximage_images_alter_carimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carafterfiximage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.get_image_fix),
        ),
    ]
