# Generated by Django 4.2 on 2024-06-24 15:58

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_alter_carafterfiximage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=car.models.get_image_name),
        ),
    ]
