# Generated by Django 4.2 on 2024-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_alter_car_car_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='car_type',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='approve_status',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'รออนุมัติ'), ('approve', 'อนุมัติ'), ('reject', 'ไม่อนุมัติ'), ('cancel', 'ยกเลิก'), ('done', 'เสร็จสิ้น')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'พร้อมใช้งาน'), ('pending', 'จอง'), ('wait', 'รอดำเนินการ'), ('inuse', 'ใช้งานอยู่'), ('fix', 'ซ่อมบำรุง'), ('not_ready', 'ไม่พร้อมใช้งาน')], default='ready', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carfix',
            name='approve_status',
            field=models.CharField(blank=True, choices=[('pending', 'รออนุมัติ'), ('approve', 'อนุมัติ'), ('reject', 'ไม่อนุมัติ'), ('cancel', 'ยกเลิก'), ('done', 'เสร็จสิ้น')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carfix',
            name='fix_status',
            field=models.CharField(blank=True, choices=[('pending', 'รอดำเนินการ'), ('in_maintenance', 'กําลังซ่อม'), ('finished', 'เสร็จสิ้น')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carfix',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carfix',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ApproveStatus',
        ),
        migrations.DeleteModel(
            name='CarFixStatus',
        ),
        migrations.DeleteModel(
            name='CarStatus',
        ),
    ]
