# Generated by Django 4.2 on 2024-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_rename_type_car_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('van', 'รถตู้'), ('truck', 'รถบรรทุก'), ('bus', 'รถบัส'), ('wagon', 'รถระบะ'), ('other', 'อื่นๆ')], default='van', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
