# Generated by Django 4.2 on 2024-06-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0052_alter_rejectreturnbillnote_options_and_more'),
        ('account', '0006_alter_profile_options'),
        ('car', '0023_alter_car_car_avatar'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('CR', 'ด่วนมาก'), ('UR', 'ด่วน'), ('NR', 'ปกติ'), ('OT', 'อื่นๆ')], default='NR', max_length=2)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='job_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oilreimburesment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oilreimburesment',
            name='oil_type',
            field=models.CharField(blank=True, choices=[('BZ', 'เบนซิน'), ('DS', 'ดีเซล')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='oilreimburesment',
            name='operaion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_request', to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='approver_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='approver_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_start', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationcar',
            name='car_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_car', to='car.carbooking'),
        ),
        migrations.AlterField(
            model_name='operationparcelrequest',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests', to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='operationparcelrequest',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_request', to='parcel.parcelrequest'),
        ),
        migrations.AlterField(
            model_name='operationparcelreturn',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_returns', to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='operationparcelreturn',
            name='parcel_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_return', to='parcel.parcelreturn'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkPlace',
        ),
        migrations.AddField(
            model_name='task',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='operation.operation'),
        ),
        migrations.AddField(
            model_name='task',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workplace', to='account.department'),
        ),
    ]
