# Generated by Django 4.2 on 2024-06-30 17:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_operation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
