# Generated by Django 4.2 on 2024-06-30 17:42

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_operation_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='user',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='oilreimburesment',
            name='approve_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
