# Generated by Django 4.2 on 2024-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_operation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
