# Generated by Django 4.2 on 2024-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='other_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(choices=[('WA', 'รอดำเนินการ'), ('IP', 'กำลังดำเนินการ'), ('DO', 'เสร็จสิ้น'), ('DF', 'ร่าง')], default='DF', max_length=2),
        ),
    ]
