# Generated by Django 4.2 on 2024-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_team_accepted_team_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(choices=[('WA', 'รอดำเนินการ'), ('IP', 'กำลังดำเนินการ'), ('DO', 'เสร็จสิ้น'), ('LD', 'หัวหน้าชุดตรวจสอบ'), ('DF', 'ร่าง')], default='DF', max_length=2),
        ),
    ]
