# Generated by Django 4.2 on 2024-07-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_alter_operation_operation_status'),
    ]

    operations = [
    ]
