# Generated by Django 4.2 on 2024-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_alter_teammember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcar',
            name='own_car',
            field=models.BooleanField(default=False),
        ),
    ]
