# Generated by Django 4.2 on 2024-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_operationcar_own_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationcar',
            name='own_car',
        ),
        migrations.AddField(
            model_name='operation',
            name='own_car',
            field=models.BooleanField(default=False),
        ),
    ]
