# Generated by Django 4.2 on 2024-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_remove_operationcar_own_car_operation_own_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='own_car',
            field=models.BooleanField(default=True),
        ),
    ]
