# Generated by Django 4.2 on 2024-08-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0015_alter_operation_own_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOperationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'รอดำเนินการ'), ('CL', 'ปิด')], default='PD', max_length=2)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placenote', to='account.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placenote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
