# Generated by Django 4.2 on 2024-08-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_placeoperationnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationcar',
            old_name='car_book',
            new_name='car_booking',
        ),
    ]
