# Generated by Django 4.2 on 2024-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_rename_car_book_operationcar_car_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='approve_status',
            field=models.CharField(blank=True, choices=[('AP', 'อนุมัติ'), ('WO', 'รออนุมัติเปิดงาน'), ('WC', 'รออนุมัติปิดงาน'), ('CL', 'ปิดงาน'), ('RJ', 'ไม่อนุมัติ')], max_length=2, null=True),
        ),
    ]
