# Generated by Django 4.2 on 2024-08-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_alter_operation_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='operation.operation'),
        ),
    ]
