# Generated by Django 4.2 on 2024-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_alter_allowance_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancewithdraw',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
