# Generated by Django 4.2 on 2024-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_allowancewithdraw_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerefund',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
