# Generated by Django 4.2 on 2024-10-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_allowancerefund_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationparcelrequest',
            old_name='parcel',
            new_name='parcel_request',
        ),
        migrations.AlterField(
            model_name='allowancerefund',
            name='allowance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='operation.allowance'),
        ),
    ]
