# Generated by Django 4.2 on 2024-11-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0013_alter_inform_options'),
        ('operation', '0024_rename_parcel_operationparcelrequest_parcel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='inform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inform.inform'),
        ),
    ]
