# Generated by Django 4.2 on 2024-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_alter_operation_inform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(choices=[('WA', 'รอดำเนินการ'), ('IP', 'กำลังดำเนินการ'), ('DO', 'เสร็จสิ้น'), ('DF', 'ร่าง')], default='DF', max_length=2),
        ),
    ]
