# Generated by Django 4.2 on 2024-11-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0013_alter_inform_options'),
        ('operation', '0027_alter_operation_operation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='inform',
        ),
        migrations.CreateModel(
            name='OperationInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', to='inform.inform')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', to='operation.operation')),
            ],
            options={
                'verbose_name': 'Operation Inform',
            },
        ),
    ]
