# Generated by Django 4.2 on 2024-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_remove_operation_inform_operationinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PD', 'รอดำเนินการ'), ('CL', 'ปิดงาน')], default='PD', max_length=2),
        ),
    ]
