# Generated by Django 4.2 on 2024-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0003_alter_announce_is_type_alter_announce_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
