# Generated by Django 4.2 on 2024-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0005_alter_announce_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'ประกาศ'), ('DONE', 'เสร็จสิ้น')], default='PUBLISH', max_length=200),
        ),
    ]
