# Generated by Django 4.2 on 2023-10-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_profile_department'),
        ('asset', '0014_itemlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_department', to='account.department')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Request Bills',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qauntity', models.PositiveIntegerField(default=1)),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.requestbill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Request Items',
            },
        ),
        migrations.CreateModel(
            name='RequestBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_approve', models.PositiveIntegerField(default=1)),
                ('approve_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.requestbill')),
            ],
            options={
                'verbose_name_plural': 'Request Bill Details',
            },
        ),
    ]
