# Generated by Django 4.2 on 2023-10-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='approve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestbilldetail',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_detail', to='parcel.requestbill'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='parcel.requestbill'),
        ),
    ]
