# Generated by Django 4.2 on 2023-10-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_department'),
        ('parcel', '0002_alter_requestbilldetail_approve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbill',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_receiver', to='account.profile'),
        ),
    ]
