# Generated by Django 4.2 on 2023-10-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_department'),
        ('parcel', '0003_alter_requestbill_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbill',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billdepartment', to='account.department'),
        ),
        migrations.AlterField(
            model_name='requestbilldetail',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billdetail', to='parcel.requestbill'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billitems', to='parcel.requestbill'),
        ),
    ]
