# Generated by Django 4.2 on 2023-10-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_alter_stockitem_status'),
        ('parcel', '0006_rename_is_paid_requestbilldetail_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.category'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem'),
        ),
    ]
