# Generated by Django 4.2 on 2023-11-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0007_requestitem_category_alter_requestitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
