# Generated by Django 4.2 on 2023-11-15 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0010_alter_requestitem_quantity_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestbill',
            name='receiver',
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='paider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_paider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_receiver', to='account.profile'),
        ),
        migrations.CreateModel(
            name='BillNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.requestbill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bill Notes',
            },
        ),
    ]
