# Generated by Django 4.2 on 2023-11-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0012_remove_requestbilldetail_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billnote',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcel.requestbill'),
        ),
    ]
