# Generated by Django 4.2 on 2023-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0013_alter_billnote_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billnote',
            name='quantity_check',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='approve_status',
            field=models.CharField(choices=[('APPROVED', 'อนุมัติ'), ('WAIT', 'รออนุมัติ'), ('UNAPPROVED', 'ยังไม่อนุมัติ')], default='WAIT', max_length=50),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='item_control',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='job_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='money_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='request_case',
            field=models.CharField(choices=[('BASIC', 'ขั้นต้น'), ('REPLACE', 'ทดแทน'), ('BORROW', 'ยืม')], default='BASIC', max_length=50),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='request_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestbilldetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
