# Generated by Django 4.2 on 2023-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0015_requestbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='item_control',
            field=models.CharField(blank=True, default='ส.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestbilldetail',
            name='item_type',
            field=models.CharField(blank=True, default='2 และ 4', max_length=50, null=True),
        ),
    ]
