# Generated by Django 4.2 on 2023-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0016_alter_requestbilldetail_item_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestbilldetail',
            name='approved',
        ),
        migrations.AlterField(
            model_name='requestbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ร่าง'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('WAITING', 'รอตรวจสอบ'), ('DONE', 'เสร็จสิ้น')], default='DRAFT', max_length=50),
        ),
    ]
