# Generated by Django 4.2 on 2023-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0017_remove_requestbilldetail_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ร่าง'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('DONE', 'เสร็จสิ้น')], default='DRAFT', max_length=50),
        ),
    ]
