# Generated by Django 4.2 on 2023-12-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0018_alter_requestbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billdetail', to='parcel.requestbill'),
        ),
    ]
