# Generated by Django 4.2 on 2023-12-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0019_alter_requestbilldetail_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
