# Generated by Django 4.2 on 2023-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0021_alter_requestitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ร่าง'), ('REQUEST', 'ขอเบิก'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('DONE', 'เสร็จสิ้น')], default='DRAFT', max_length=50),
        ),
    ]
