# Generated by Django 4.2 on 2023-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0023_remove_requestitem_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='approve_status',
            field=models.CharField(choices=[('APPROVED', 'อนุมัติ'), ('WAIT', 'รออนุมัติ'), ('UNAPPROVED', 'ไม่อนุมัติ')], default='WAIT', max_length=50),
        ),
    ]
