# Generated by Django 4.2 on 2023-12-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0025_rejectbillnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='price',
        ),
    ]
