# Generated by Django 4.2 on 2024-01-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0026_remove_requestitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbilldetail',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
