# Generated by Django 4.2 on 2024-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0027_requestbilldetail_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
