# Generated by Django 4.2 on 2024-01-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0028_alter_requestbilldetail_approve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbilldetail',
            name='request_approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
