# Generated by Django 4.2 on 2024-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0029_requestbilldetail_request_approve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbilldetail',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('PAID', 'เตรียมจ่ายพัสดุ'), ('RECEIVED', 'รับพัสดุแล้ว')], max_length=50, null=True),
        ),
    ]
