# Generated by Django 4.2 on 2024-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0030_requestbilldetail_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='quantity_approve',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
