# Generated by Django 4.2 on 2024-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0031_alter_requestitem_quantity_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbilldetail',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('PAID', 'เตรียมจ่ายพัสดุ'), ('RECIVED', 'รับพัสดุแล้ว')], max_length=50, null=True),
        ),
    ]
