# Generated by Django 4.2 on 2024-01-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0017_remove_itemonhand_updated_at'),
        ('parcel', '0033_alter_requestbilldetail_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcel.requestbill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.stockitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Set Items',
            },
        ),
    ]
