# Generated by Django 4.2 on 2024-01-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0035_setitem_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetItem',
        ),
    ]
