# Generated by Django 4.2 on 2024-02-15 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_profile_options'),
        ('parcel', '0036_delete_setitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestBill',
            new_name='ParcelRequest',
        ),
        migrations.RenameModel(
            old_name='BillNote',
            new_name='ParcelRequestNote',
        ),
        migrations.AlterModelOptions(
            name='parcelrequest',
            options={'verbose_name_plural': 'Parcel Request Bills'},
        ),
        migrations.AlterModelOptions(
            name='parcelrequestnote',
            options={'verbose_name_plural': 'Parcel Request Bill Notes'},
        ),
        migrations.AlterModelOptions(
            name='rejectbillnote',
            options={'verbose_name_plural': 'Reject Parcel Request Bill Notes'},
        ),
    ]
