# Generated by Django 4.2 on 2024-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0038_checknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbilldetail',
            name='paid_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
