# Generated by Django 4.2 on 2024-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0039_requestbilldetail_paid_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckNote',
        ),
    ]
