# Generated by Django 4.2 on 2024-04-01 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0040_delete_checknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'ร่าง'), ('REQUEST', 'ขอคืน'), ('WAIT', 'รอการตรวจสอบ'), ('DONE', 'ตรวจสอบเสร็จสิ้น')], default='WAIT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('department_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_return', to='account.department')),
                ('stock_reciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reciever', to='account.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parcel Return Bills',
            },
        ),
        migrations.CreateModel(
            name='RejectReturnBillNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcelreturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('approve_status', models.CharField(choices=[('APPROVED', 'อนุมัติ'), ('WAIT', 'รออนุมัติ'), ('UNAPPROVED', 'ไม่อนุมัติ')], default='WAIT', max_length=50)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, choices=[('WAIT', 'รอการตรวจสอบ'), ('RETURNED', 'ส่งคืนแล้ว')], max_length=50, null=True)),
                ('request_case', models.CharField(blank=True, choices=[('BROKEN', 'เสีย'), ('REPORT', 'แจ้งเตือน'), ('RETURN', 'ส่งคืน'), ('NORMAL', 'ปกติ'), ('EXCEED', 'เกินกําหนด'), ('BORROW', 'ยืม')], max_length=50, null=True)),
                ('item_type', models.CharField(blank=True, default='2 และ 4', max_length=50, null=True)),
                ('item_control', models.CharField(blank=True, default='ส.', max_length=50, null=True)),
                ('money_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True)),
                ('request_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_approve_date', models.DateTimeField(blank=True, null=True)),
                ('return_no', models.CharField(blank=True, max_length=10, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billdetail', to='parcel.parcelreturn')),
                ('controler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_controler', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parcel Return Bill Details',
            },
        ),
        migrations.CreateModel(
            name='ParcelReturnBillNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcelreturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
