# Generated by Django 4.2 on 2024-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0042_parcelreturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ร่าง'), ('REQUEST', 'ขอคืน'), ('WAIT', 'รอการตรวจสอบ'), ('DONE', 'ตรวจสอบเสร็จสิ้น')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcelreturndetail',
            name='request_case',
            field=models.CharField(blank=True, choices=[('Wear and tear', 'ใช้ในราชการไม่ได้เนื่องจากชำรุดตามสภาพ'), ('Investigation report', 'ใช้ในราชการไม่ได้ตามรายงานการสอบสวน'), ('Compensation', 'ใช้ในราชการไม่ได้ซึ่งต้องชดใช้ค่าเสียหาย'), ('Serviceable', 'ใช้ในราชการได้'), ('Exess', 'เกินอัตรา'), ('On loan', 'ยืม')], max_length=50, null=True),
        ),
    ]
