# Generated by Django 4.2 on 2024-04-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0043_alter_parcelreturn_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelreturndetail',
            old_name='request_case',
            new_name='return_case',
        ),
    ]
