# Generated by Django 4.2 on 2024-04-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0044_rename_request_case_parcelreturndetail_return_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelreturn',
            old_name='stock_reciever',
            new_name='stock',
        ),
    ]
