# Generated by Django 4.2 on 2024-04-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0045_rename_stock_reciever_parcelreturn_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelreturnitem',
            options={'verbose_name_plural': 'Return Items'},
        ),
    ]
