# Generated by Django 4.2 on 2024-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0046_alter_parcelreturnitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelreturnitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
