# Generated by Django 4.2 on 2024-05-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0047_parcelreturnitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelreturndetail',
            name='request_reference',
        ),
    ]
