# Generated by Django 4.2 on 2024-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0048_remove_parcelreturndetail_request_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelreturn',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
