# Generated by Django 4.2 on 2024-05-09 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0049_parcelreturn_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelreturndetail',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelreturndetail',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelreturndetail',
            name='control_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
