# Generated by Django 4.2 on 2024-05-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0050_parcelreturndetail_checked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelreturnbillnote',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_note', to='parcel.parcelreturn'),
        ),
    ]
