# Generated by Django 4.2 on 2024-06-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0051_alter_parcelreturnbillnote_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectreturnbillnote',
            options={'verbose_name_plural': 'Reject Return Bill Notes'},
        ),
        migrations.RemoveField(
            model_name='parcelreturndetail',
            name='checked_date',
        ),
        migrations.RemoveField(
            model_name='parcelreturndetail',
            name='checker',
        ),
    ]
