#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : settings.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 22 2022, 15:05 265
# Last Modified Date: Mon Jun, 24 2024, 16:00 176
# Last Modified By  : lu5her <lu5her@mail>
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ENV = Path.joinpath(BASE_DIR, '.env')
config = dotenv_values(".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-61v=ike9p3)ol&xa33bkw=&ogpw^&*jnh+0zt3afnoq8u5q7)3"
# SECRET_KEY = os.environ['SECRET_KEY']
# SECRET_KEY = config["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = config["DEBUG"]

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # external app
    "crispy_forms",
    "ckeditor",
    "debug_toolbar",
    "django_extensions",
    # internal app
    "account",
    "announce",
    "document",
    "journal",
    "assign",
    "car",
    "asset",
    "inform",
    "repair",
    "parcel",
    "operation",
    "cart.apps.CartConfig",
]
CRISPY_TEMPLATE_PACK = "bootstrap4"

CKEDITOR_CONFIGS = {
    "default": {
        "height": "full",
        "width": "full",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # for render app context
                "account.context_processors.assign_not_accepted",
                "account.context_processors.announce_not_read",
                "account.context_processors.document_not_accepted",
                "account.context_processors.new_inform",
                "account.context_processors.car_booking",
                "account.context_processors.count_total",
                # 'account.context_processors.items_on_hand',
                "parcel.context_processors.items_on_hand",
                # "car.context_processors.car_booking",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    Path.joinpath(BASE_DIR, "static"),
]
# STATIC_ROOT = Path.joinpath(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "media/"
MEDIA_ROOT = Path.joinpath(BASE_DIR, "media")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

X_FRAME_OPTIONS = "SAMEORIGIN"

INTERNAL_IPS = [
    "127.0.0.1",
    # 'localhost',
]

JAZZMIN_SETTINGS = {
    "site_title": "TCC Admin",
    "site_header": "TCC Admin",
    "site_logo": "assets/img/tcc_logo.png",
    "copyright": "Telecommunication and Network",
    "welcome_sign": "Welcome, TCC Admin",
    #######
    # css #
    #######
    # "custom_css": "assets/css/style.css",
}

# for use out by ngrok-free
CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app"]

# for cart sessions
CART_SESSION_ID = "cart"
